In [119]:
import pandas as pd
import numpy as np

In [120]:
data = pd.read_csv("data/previous_data.csv")

In [121]:
data.head()

,X1,X2,X3,X4,X5,X6,X7,X8,X9,X10,...,X15N2,X15N3,X15N4,X15N5,X15N6,X15N7,X15N8,X15N9,X15N10,X15N11
0,0,1,2,1,1,6,1,0,1,3,...,2,1,1,4,2,1,3,1,2,2
1,0,0,2,0,1,2,4,0,0,2,...,3,3,2,3,1,1,2,2,2,3
2,0,4,2,0,0,4,4,0,2,1,...,1,1,1,1,1,1,1,1,1,1
3,0,0,1,1,1,4,1,3,2,2,...,1,1,1,1,1,1,1,1,1,1
4,0,0,2,1,1,6,4,4,1,2,...,4,4,2,2,2,2,3,2,2,3

In [122]:
features = ["X2", "X3", "X4", "X5", "X6", "X7", "X8", "X11.1", "X11.2", "X14.8", "X14.9", "X14.10", "X17.4", "X17.5",
            "X17.6", "X18.1", "X18.2", "X18.3", "X18.4", "X18.5", "X18.6", "X18.7", "X19.1", "X19.2", "X19.3", "X20.1", "X20.2",
            "X20.3", "X21", "X22.1", "X22.2", "X22.3", "X22.4", "X22.5", "X22.6", "X24", "X25"]

In [123]:
data = data.dropna(subset=features)

In [124]:
data = data[features].copy()

In [125]:
data

,X2,X3,X4,X5,X6,X7,X8,X11.1,X11.2,X14.8,...,X20.3,X21,X22.1,X22.2,X22.3,X22.4,X22.5,X22.6,X24,X25
0,1,2,1,1,6,1,0,0,3,0,...,2,0,0,1,0,1,1,1,2,2
1,0,2,0,1,2,4,0,1,3,0,...,0,1,1,1,1,2,1,0,0,0
2,4,2,0,0,4,4,0,0,0,0,...,0,1,0,1,0,1,0,0,2,1
3,0,1,1,1,4,1,3,0,1,0,...,0,0,0,0,0,0,0,0,1,1
4,0,2,1,1,6,4,4,0,3,0,...,0,0,0,0,0,0,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,0,2,0,0,2,2,1,1,3,0,...,0,1,0,0,1,1,0,0,0,0
190,0,2,0,4,4,4,3,0,0,0,...,2,0,0,0,1,1,0,1,2,1
191,1,1,1,3,4,1,3,0,4,0,...,0,0,0,0,0,0,0,0,0,0
192,0,1,1,7,4,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
193,0,2,0,3,6,4,4,0,1,0,...,0,1,0,0,0,0,0,0,0,0

# Pseudocode

## High level

1. Scale data to standardize values
2. Initialize random centroids
3. Get labels for each data point
4. Create new centroids
5. Plot the centroids
6. Repeat 3-5 until the centroids stop changing

In [126]:
import pandas as pd
import numpy as np

# Strip spaces and replace empty strings with NaN
data = data.replace(r'^\s*$', np.nan, regex=True).fillna(0)

# Convert to integer
data = data.astype(int)

# Check data types after conversion
print(data.dtypes)

X2        int64
X3        int64
X4        int64
X5        int64
X6        int64
X7        int64
X8        int64
X11.1     int64
X11.2     int64
X14.8     int64
X14.9     int64
X14.10    int64
X17.4     int64
X17.5     int64
X17.6     int64
X18.1     int64
X18.2     int64
X18.3     int64
X18.4     int64
X18.5     int64
X18.6     int64
X18.7     int64
X19.1     int64
X19.2     int64
X19.3     int64
X20.1     int64
X20.2     int64
X20.3     int64
X21       int64
X22.1     int64
X22.2     int64
X22.3     int64
X22.4     int64
X22.5     int64
X22.6     int64
X24       int64
X25       int64
dtype: object

In [127]:
data = ((data - data.min()) / (data.max() - data.min())) * 10 + 1

In [128]:
data.describe()

,X2,X3,X4,X5,X6,X7,X8,X11.1,X11.2,X14.8,...,X20.3,X21,X22.1,X22.2,X22.3,X22.4,X22.5,X22.6,X24,X25
count,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,...,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000
mean,2.348797,4.416789,8.319588,3.828608,5.904271,5.982818,4.339061,1.680412,5.515464,1.515464,...,1.817378,3.641753,1.567010,1.762887,1.907216,1.938144,1.381443,1.329897,3.809278,2.378866
std,2.589624,2.167333,4.440852,2.019162,2.170751,2.584160,2.696858,1.479017,3.177360,2.216815,...,2.111139,2.250333,1.322638,1.614527,1.590662,1.741386,1.203994,1.158180,4.068037,2.570159
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,2.428571,1.000000,2.250000,3.857143,3.083333,1.000000,1.000000,3.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
50%,1.000000,3.857143,11.000000,2.250000,6.714286,7.666667,4.333333,1.000000,5.000000,1.000000,...,1.000000,3.500000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,2.666667,6.714286,11.000000,6.000000,6.714286,7.666667,7.388889,1.000000,9.000000,1.000000,...,1.000000,3.500000,1.000000,3.000000,3.000000,3.000000,1.000000,1.000000,6.000000,3.500000
max,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,...,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000

In [129]:
data.head()

,X2,X3,X4,X5,X6,X7,X8,X11.1,X11.2,X14.8,...,X20.3,X21,X22.1,X22.2,X22.3,X22.4,X22.5,X22.6,X24,X25
0,2.666667,3.857143,11.0,2.25,9.571429,2.666667,1.000000,1.0,7.0,1.0,...,3.857143,1.0,1.0,3.0,1.0,3.0,3.0,3.0,11.0,6.0
1,1.000000,3.857143,1.0,2.25,3.857143,7.666667,1.000000,3.0,7.0,1.0,...,1.000000,3.5,3.5,3.0,3.0,5.0,3.0,1.0,1.0,1.0
2,7.666667,3.857143,1.0,1.00,6.714286,7.666667,1.000000,1.0,1.0,1.0,...,1.000000,3.5,1.0,3.0,1.0,3.0,1.0,1.0,11.0,3.5
3,1.000000,2.428571,11.0,2.25,6.714286,2.666667,4.333333,1.0,3.0,1.0,...,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,6.0,3.5
4,1.000000,3.857143,11.0,2.25,9.571429,7.666667,5.444444,1.0,7.0,1.0,...,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,11.0,1.0

In [130]:
def random_centroids(data, k):
    centroids = []
    for i in range(k):
        centroid = data.apply(lambda x: float(x.sample()))
        centroids.append(centroid)
    return pd.concat(centroids, axis=1)

In [131]:
centroids = random_centroids(data, 5)

C:\Users\leona\AppData\Local\Temp\ipykernel_15560\1428031141.py:4: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  centroid = data.apply(lambda x: float(x.sample()))

In [132]:
centroids

                0          1          2          3          4
X2       1.000000   1.000000   1.000000   1.000000   1.000000
X3       2.428571   1.000000   6.714286   8.142857   6.714286
X4       1.000000  11.000000  11.000000  11.000000  11.000000
X5       2.250000   7.250000   6.000000   6.000000   6.000000
X6       6.714286   6.714286   5.285714   5.285714   6.714286
X7       7.666667   7.666667   7.666667   1.000000   9.333333
X8       7.666667   1.000000   7.666667   4.333333   4.333333
X11.1    1.000000   1.000000   1.000000   1.000000   1.000000
X11.2    9.000000   3.000000   1.000000   9.000000   3.000000
X14.8    1.000000   1.000000   1.000000   1.000000   1.000000
X14.9    1.000000   1.000000   1.000000   1.000000   1.000000
X14.10   1.000000   1.000000   1.000000   1.000000   1.000000
X17.4    3.000000   5.000000   7.000000   5.000000   5.000000
X17.5   11.000000   1.000000   7.000000   5.000000   1.000000
X17.6    3.000000   7.000000   3.000000   7.000000   5.000000
X18.1    1.000000   1.000000   1.000000   1.000000   3.000000
X18.2    3.000000   1.000000   1.000000   1.000000   5.000000
X18.3    7.000000   1.000000   7.000000   3.000000   1.000000
X18.4    1.000000   1.000000   1.000000   1.000000   1.000000
X18.5    3.000000   3.000000   1.000000   1.000000   1.000000
X18.6    1.000000   1.000000   3.000000   1.000000   7.000000
X18.7    1.000000   1.000000   1.000000   1.000000   3.000000
X19.1    1.000000   1.000000   1.000000   1.000000   1.000000
X19.2    1.000000   1.000000   9.571429   1.000000   1.000000
X19.3    3.857143   1.000000   2.428571   2.428571   1.000000
X20.1    1.000000   1.000000   1.000000   1.000000   1.000000
X20.2    1.000000   1.000000   1.000000   1.000000   3.857143
X20.3    1.000000   1.000000   1.000000   1.000000   2.428571
X21      6.000000   6.000000   6.000000   1.000000   3.500000
X22.1    1.000000   1.000000   3.500000   1.000000   1.000000
X22.2    1.000000   3.000000   5.000000   1.000000   1.000000
X22.3    1.000000   1.000000   1.000000   1.000000   3.000000
X22.4    1.000000  11.000000   1.000000   1.000000   1.000000
X22.5    1.000000   3.000000   1.000000   1.000000   1.000000
X22.6    1.000000   1.000000   1.000000   1.000000   1.000000
X24      6.000000  11.000000  11.000000   1.000000   1.000000
X25      1.000000   1.000000   6.000000   1.000000  11.000000

In [133]:
def get_labels(data, centroids):
    distances = centroids.apply(lambda x: np.sqrt(((data - x) ** 2).sum(axis=1)))
    return distances.idxmin(axis=1)

In [134]:
labels = get_labels(data, centroids)

In [135]:
labels.value_counts()

3    117
0     38
2     17
4     14
1      8
Name: count, dtype: int64

In [136]:
def new_centroids(data, labels, k):
    centroids = data.groupby(labels).apply(lambda x: np.exp(np.log(x).mean())).T
    return centroids

In [137]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from IPython.display import clear_output

In [138]:
def plot_clusters(data, labels, centroids, iteration):
    pca = PCA(n_components=2)
    data_2d = pca.fit_transform(data)
    centroids_2d = pca.transform(centroids.T)
    clear_output(wait=True)
    plt.title(f'Iteration {iteration}')
    plt.scatter(x=data_2d[:,0], y=data_2d[:,1], c=labels)
    plt.scatter(x=centroids_2d[:,0], y=centroids_2d[:,1])
    plt.show()

In [139]:
max_iterations = 100
centroid_count = 3

centroids = random_centroids(data, centroid_count)
old_centroids = pd.DataFrame()
iteration = 1

while iteration < max_iterations and not centroids.equals(old_centroids):
    old_centroids = centroids
    
    labels = get_labels(data, centroids)
    centroids = new_centroids(data, labels, centroid_count)
    plot_clusters(data, labels, centroids, iteration)
    iteration += 1

In [140]:
centroids

               0         1          2
X2      1.936096  1.532984   1.541502
X3      3.572854  4.175872   3.892590
X4      1.000000  2.919464  11.000000
X5      2.739346  3.501374   3.368697
X6      4.608835  5.452505   5.705667
X7      6.005152  4.522286   5.183636
X8      2.507774  3.690298   3.272715
X11.1   1.235248  1.352878   1.396890
X11.2   3.091189  4.272210   4.536497
X14.8   1.202561  1.290585   1.061255
X14.9   1.096613  1.107426   1.020015
X14.10  1.096613  1.052343   1.000000
X17.4   5.011239  5.943111   5.133510
X17.5   2.768553  5.710684   3.344479
X17.6   3.937543  5.987898   5.471303
X18.1   1.525837  2.406763   1.398364
X18.2   1.430010  2.771159   1.861955
X18.3   2.247578  4.887587   2.613054
X18.4   1.184141  2.899540   1.335184
X18.5   1.344175  2.080302   1.255570
X18.6   1.235248  2.377266   1.229675
X18.7   1.135148  2.336101   1.211885
X19.1   1.084001  2.227342   1.118809
X19.2   1.000000  3.674379   1.171779
X19.3   1.034716  2.675580   1.250119
X20.1   1.158650  2.764991   1.409823
X20.2   1.053292  2.202102   1.330589
X20.3   1.090762  2.087711   1.172833
X21     3.627268  2.710510   2.892170
X22.1   1.335224  1.522668   1.203119
X22.2   1.370845  1.882963   1.250617
X22.3   1.623273  2.051614   1.328981
X22.4   1.314128  2.165248   1.343981
X22.5   1.088182  1.416099   1.122232
X22.6   1.043160  1.405997   1.086785
X24     1.444672  4.276746   1.783558
X25     1.280935  2.512235   1.421298

In [141]:
labels.value_counts()

2    121
1     47
0     26
Name: count, dtype: int64

In [142]:
data[labels == 0][features]

,X2,X3,X4,X5,X6,X7,X8,X11.1,X11.2,X14.8,...,X20.3,X21,X22.1,X22.2,X22.3,X22.4,X22.5,X22.6,X24,X25
1,1.000000,3.857143,1.0,2.25,3.857143,7.666667,1.000000,3.0,7.0,1.0,...,1.000000,3.5,3.5,3.0,3.0,5.0,3.0,1.0,1.0,1.0
2,7.666667,3.857143,1.0,1.00,6.714286,7.666667,1.000000,1.0,1.0,1.0,...,1.000000,3.5,1.0,3.0,1.0,3.0,1.0,1.0,11.0,3.5
42,1.000000,3.857143,1.0,2.25,5.285714,7.666667,4.333333,1.0,1.0,1.0,...,1.000000,6.0,1.0,1.0,1.0,1.0,1.0,1.0,6.0,1.0
47,1.000000,8.142857,1.0,2.25,3.857143,6.000000,5.444444,1.0,7.0,1.0,...,1.000000,8.5,3.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0
51,1.000000,2.428571,1.0,2.25,5.285714,7.666667,1.000000,1.0,9.0,11.0,...,1.000000,3.5,3.5,1.0,9.0,3.0,1.0,1.0,1.0,1.0
59,1.000000,2.428571,1.0,2.25,3.857143,4.333333,1.000000,1.0,3.0,1.0,...,1.000000,3.5,1.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0
64,1.000000,3.857143,1.0,1.00,5.285714,7.666667,7.666667,1.0,1.0,11.0,...,1.000000,6.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0
105,1.000000,2.428571,1.0,6.00,3.857143,7.666667,5.444444,3.0,3.0,1.0,...,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
115,1.000000,6.714286,1.0,2.25,2.428571,7.666667,5.444444,1.0,9.0,1.0,...,1.000000,11.0,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0
127,1.000000,5.285714,1.0,2.25,3.857143,7.666667,5.444444,3.0,9.0,1.0,...,1.000000,11.0,3.5,1.0,5.0,3.0,3.0,3.0,1.0,1.0
139,1.000000,2.428571,1.0,6.00,6.714286,2.666667,1.000000,1.0,3.0,1.0,...,1.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
141,6.000000,5.285714,1.0,6.00,5.285714,7.666667,1.000000,1.0,5.0,1.0,...,1.000000,1.0,3.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0
145,1.000000,5.285714,1.0,6.00,3.857143,7.666667,6.555556,1.0,3.0,1.0,...,1.000000,3.5,1.0,1.0,1.0,1.0,1.0,1.0,6.0,1.0
146,1.000000,1.000000,1.0,2.25,2.428571,2.666667,1.000000,1.0,1.0,1.0,...,1.000000,6.0,3.5,5.0,1.0,1.0,1.0,1.0,1.0,1.0
147,1.000000,2.428571,1.0,6.00,2.428571,7.666667,4.333333,1.0,3.0,1.0,...,1.000000,3.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
148,1.000000,3.857143,1.0,6.00,3.857143,7.666667,1.000000,1.0,5.0,1.0,...,9.571429,3.5,1.0,3.0,1.0,1.0,1.0,1.0,1.0,8.5
150,1.000000,5.285714,1.0,2.25,2.428571,7.666667,4.333333,1.0,9.0,1.0,...,1.000000,3.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
155,6.000000,5.285714,1.0,2.25,6.714286,7.666667,3.222222,3.0,9.0,1.0,...,1.000000,1.0,1.0,3.0,1.0,1.0,1.0,1.0,1.0,1.0
156,1.000000,2.428571,1.0,2.25,5.285714,7.666667,5.444444,1.0,1.0,1.0,...,1.000000,3.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
159,11.000000,2.428571,1.0,2.25,9.571429,6.000000,1.000000,1.0,1.0,1.0,...,1.000000,3.5,1.0,3.0,3.0,1.0,1.0,1.0,1.0,1.0
163,4.333333,2.428571,1.0,4.75,6.714286,4.333333,1.000000,1.0,5.0,1.0,...,1.000000,3.5,1.0,1.0,3.0,1.0,1.0,1.0,6.0,6.0
166,11.000000,2.428571,1.0,4.75,5.285714,7.666667,4.333333,1.0,1.0,1.0,...,1.000000,3.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
168,6.000000,2.428571,1.0,2.25,6.714286,1.000000,1.000000,1.0,1.0,1.0,...,1.000000,3.5,1.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0
173,7.666667,6.714286,1.0,6.00,3.857143,7.666667,7.666667,1.0,9.0,1.0,...,1.000000,3.5,1.0,1.0,1.0,1.0,1.0,1.0,6.0,3.5
183,4.333333,6.714286,1.0,1.00,9.571429,7.666667,5.444444,1.0,1.0,1.0,...,1.000000,11.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
189,1.000000,3.857143,1.0,1.00,3.857143,4.333333,2.111111,3.0,7.0,1.0,...,1.000000,3.5,1.0,1.0,3.0,3.0,1.0,1.0,1.0,1.0

In [143]:
from sklearn.cluster import KMeans

In [144]:
kmeans = KMeans(3)
kmeans.fit(data)

KMeans(n_clusters=3)

In [145]:
pd.DataFrame(kmeans.cluster_centers_, columns=features).T

               0          1         2
X2      2.821705   2.233596  2.111111
X3      4.189369   4.475816  4.511905
X4      1.000000  11.000000  7.250000
X5      3.732558   3.903543  3.604167
X6      5.352159   6.185602  5.404762
X7      6.193798   6.078740  5.097222
X8      4.152455   4.447069  4.101852
X11.1   1.558140   1.755906  1.500000
X11.2   4.534884   5.850394  5.500000
X14.8   2.162791   1.236220  1.833333
X14.9   1.232558   1.078740  1.833333
X14.10  1.232558   1.000000  1.416667
X17.4   5.883721   6.055118  6.666667
X17.5   4.860465   4.496063  6.416667
X17.6   5.093023   6.070866  6.750000
X18.1   1.883721   1.614173  4.416667
X18.2   2.255814   2.527559  4.333333
X18.3   3.558140   3.409449  5.833333
X18.4   1.837209   1.771654  5.083333
X18.5   1.604651   1.598425  3.833333
X18.6   1.651163   1.488189  4.333333
X18.7   1.465116   1.503937  4.500000
X19.1   1.764120   1.326209  4.869048
X19.2   2.129568   1.573678  6.595238
X19.3   1.299003   1.708661  6.714286
X20.1   2.124031   2.115486  5.375000
X20.2   1.365449   1.731159  4.392857
X20.3   1.431894   1.393701  4.750000
X21     3.848837   3.559055  3.708333
X22.1   1.465116   1.433071  2.458333
X22.2   1.837209   1.503937  3.000000
X22.3   2.116279   1.582677  3.250000
X22.4   1.930233   1.740157  3.000000
X22.5   1.093023   1.314961  2.250000
X22.6   1.186047   1.251969  2.000000
X24     3.441860   3.125984  8.083333
X25     2.453488   1.984252  4.333333