In [1]:
import pandas as pd
import numpy as np

red_flags = {"Suicide Attempt": 0.15, "Weapon": 0.05, "Gang": 0.06, "Depressed": 0.045, "Community Violence": 0.2,
             "Sexual Abuse": 0.27, "Physical Abuse": 0.07, "Hard Drug Use": 0.07}


def generate_data(number_of_people):
    data = {
        "Age": np.random.randint(16, 90, size=number_of_people),
        "Exchange_Sex": np.random.choice([0, 1], size=number_of_people, p=[0.15, 0.85]),
        "Children": np.random.choice([0, 1, 2, 3], size=number_of_people),
        "Suicide_Attempt": np.random.choice([0, 1], size=number_of_people, p=[0.25, 0.75]),
        "Jail": np.random.choice([0, 1], size=number_of_people, p=[0.25, 0.75]),
        "Male": np.random.choice([0, 1], size=number_of_people),
        "LGBQ": np.random.choice([0, 1], size=number_of_people, p=[0.2, 0.8]),
        "White": np.random.choice([0, 1], size=number_of_people),
        "Literal_Homeless": np.random.choice([0, 1], size=number_of_people, p=[0.1, 0.9]),
        "Weapon": np.random.choice([0, 1], size=number_of_people),
        "Gang": np.random.choice([0, 1], size=number_of_people, p=[0.3, 0.7]),
        "PTSD": np.random.choice([0, 1], size=number_of_people, p=[0.3, 0.7]),
        "Depressed": np.random.choice([0, 1], size=number_of_people, p=[0.4, 0.6]),
        "Community_Violence": np.random.choice([0, 1], size=number_of_people, p=[0.6, 0.4]),
        "Sexual_Abuse": np.random.choice([0, 1], size=number_of_people, p=[0.25, 0.75]),
        "Physical_Abuse": np.random.choice([0, 1], size=number_of_people, p=[0.25, 0.75]),
        "Hard_Drug_Use": np.random.choice([0, 1], size=number_of_people, p=[0.4, 0.6]),
        "Foster_Care": np.random.choice([0, 1], size=number_of_people, p=[0.15, 0.85]),
        "Job": np.random.choice([0, 1], size=number_of_people, p=[0.2, 0.8])
    }
    return pd.DataFrame(data)


def calculate_score(data):
    # Create a column to store the sum of the red flags
    data['Red_Flag_Score'] = (data['Suicide_Attempt'] * red_flags['Suicide Attempt'] +
                              data['Weapon'] * red_flags['Weapon'] +
                              data['Gang'] * red_flags['Gang'] +
                              data['Depressed'] * red_flags['Depressed'] +
                              data['Community_Violence'] * red_flags['Community Violence'] +
                              data['Sexual_Abuse'] * red_flags['Sexual Abuse'] +
                              data['Physical_Abuse'] * red_flags['Physical Abuse'] +
                              data['Hard_Drug_Use'] * red_flags['Hard Drug Use'])

    # Generate the 'Victim' column using the red flag score
    data['Victim'] = data['Red_Flag_Score'].apply(lambda x: np.random.choice([0, 1], p=[1 - x, x]))

    return data

In [4]:
df = generate_data(10)  # Generate 10 people data
df

,Age,Exchange_Sex,Children,Suicide_Attempt,Jail,Male,LGBQ,White,Literal_Homeless,Weapon,Gang,PTSD,Depressed,Community_Violence,Sexual_Abuse,Physical_Abuse,Hard_Drug_Use,Foster_Care,Job
0,30,1,1,1,1,1,1,0,1,0,1,1,1,1,1,0,1,1,0
1,38,1,0,1,1,0,1,1,1,0,1,0,1,0,1,0,1,1,1
2,61,1,2,1,1,1,1,0,1,0,1,1,0,0,1,1,0,1,1
3,71,1,2,0,0,1,0,0,1,1,0,0,1,0,1,1,0,1,1
4,55,1,3,1,1,1,1,0,1,0,1,1,0,1,1,1,0,1,1
5,48,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
6,25,1,1,1,1,0,1,0,1,1,1,0,1,1,1,1,1,1,0
7,82,1,0,1,1,1,1,0,1,1,0,1,1,1,1,1,1,1,1
8,47,1,2,1,1,0,1,0,1,0,1,1,1,1,0,1,1,0,0
9,69,1,0,1,1,0,1,1,1,0,1,1,1,0,1,0,1,1,1

In [5]:
scored_df = calculate_score(df)  # Add risk scores
scored_df

,Age,Exchange_Sex,Children,Suicide_Attempt,Jail,Male,LGBQ,White,Literal_Homeless,Weapon,...,PTSD,Depressed,Community_Violence,Sexual_Abuse,Physical_Abuse,Hard_Drug_Use,Foster_Care,Job,Red_Flag_Score,Victim
0,30,1,1,1,1,1,1,0,1,0,...,1,1,1,1,0,1,1,0,0.795,0
1,38,1,0,1,1,0,1,1,1,0,...,0,1,0,1,0,1,1,1,0.595,1
2,61,1,2,1,1,1,1,0,1,0,...,1,0,0,1,1,0,1,1,0.550,1
3,71,1,2,0,0,1,0,0,1,1,...,0,1,0,1,1,0,1,1,0.435,0
4,55,1,3,1,1,1,1,0,1,0,...,1,0,1,1,1,0,1,1,0.750,1
5,48,1,3,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,0.915,1
6,25,1,1,1,1,0,1,0,1,1,...,0,1,1,1,1,1,1,0,0.915,1
7,82,1,0,1,1,1,1,0,1,1,...,1,1,1,1,1,1,1,1,0.855,1
8,47,1,2,1,1,0,1,0,1,0,...,1,1,1,0,1,1,0,0,0.595,0
9,69,1,0,1,1,0,1,1,1,0,...,1,1,0,1,0,1,1,1,0.595,1